version = 1

# computer-generated files
[[annotations]]
path = [
	"go.sum",
	".gitignore",
	".dockerignore",
	"docker/*",
	".idea/**",
	"target/**" 
]

SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"


